// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class AccountAddress
    {
        public long Id { get; set; }
        public int MemberId { get; set; }
        public string Address { get; set; }
		public double? Latitude { get; set; }
		public double? Longitude { get; set; }
		public virtual Member Member { get; set; }
    }
}