// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class Api
    {
        public int Id { get; set; }
        public string Apiname { get; set; }
        public string Apikey { get; set; }
    }
}