// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class CommonReply
    {
        public int Id { get; set; }
        public DateTime CreateTime { get; set; }
        public string Answer { get; set; }
    }
}