// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class DeliveryViolationRecord
    {
        public int Id { get; set; }
        public int DeliveryDriversId { get; set; }
        public int ViolationId { get; set; }
        public long OrderId { get; set; }
        public DateTime ViolationDate { get; set; }

        public virtual DeliveryDriver DeliveryDrivers { get; set; }
        public virtual Order Order { get; set; }
        public virtual DeliveryViolationType Violation { get; set; }
    }
}