// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class DeliveryViolationType
    {
        public DeliveryViolationType()
        {
            DeliveryViolationRecords = new HashSet<DeliveryViolationRecord>();
        }

        public int Id { get; set; }
        public string ViolationContent { get; set; }
        public string Content { get; set; }

        public virtual ICollection<DeliveryViolationRecord> DeliveryViolationRecords { get; set; }
    }
}