// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class OrderSchedule
    {
        public int Id { get; set; }
        public long OrderId { get; set; }
        public int StatusId { get; set; }
        public DateTime MarkTime { get; set; }

        public virtual Order Order { get; set; }
        public virtual OrderStatue Status { get; set; }
    }
}