// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int IdentifyNum { get; set; }
        public long ProductId { get; set; }
        public int ProductPrice { get; set; }
        public int? ItemId { get; set; }
        public int ItemPrice { get; set; }
        public int Qty { get; set; }
        public long OrderId { get; set; }

        public virtual ProductCustomizationItem Item { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}