// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class Order
    {
        public Order()
        {
            AppealRecords = new HashSet<AppealRecord>();
            DeliveryViolationRecords = new HashSet<DeliveryViolationRecord>();
            DriverCancellationRecords = new HashSet<DriverCancellationRecord>();
            MemberViolationRecords = new HashSet<MemberViolationRecord>();
            OrderDetails = new HashSet<OrderDetail>();
            OrderSchedules = new HashSet<OrderSchedule>();
            StoreCancellationRecords = new HashSet<StoreCancellationRecord>();
            StoreViolationRecords = new HashSet<StoreViolationRecord>();
            StoreWallets = new HashSet<StoreWallet>();
        }

        public long Id { get; set; }
        public int? DeliveryDriversId { get; set; }
        public int MemberId { get; set; }
        public int StoreId { get; set; }
        public int DeliveryFee { get; set; }
        public string DeliveryAddress { get; set; }
        public int? DriverRating { get; set; }
        public int? StoreRating { get; set; }
        public string DriverComment { get; set; }
        public string StoreComment { get; set; }
        public decimal Milage { get; set; }
        public bool CreateMark { get; set; }
        public virtual DeliveryDriver DeliveryDrivers { get; set; }
        public virtual Member Member { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<AppealRecord> AppealRecords { get; set; }
        public virtual ICollection<DeliveryViolationRecord> DeliveryViolationRecords { get; set; }
        public virtual ICollection<DriverCancellationRecord> DriverCancellationRecords { get; set; }
        public virtual ICollection<MemberViolationRecord> MemberViolationRecords { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderSchedule> OrderSchedules { get; set; }
        public virtual ICollection<StoreCancellationRecord> StoreCancellationRecords { get; set; }
        public virtual ICollection<StoreViolationRecord> StoreViolationRecords { get; set; }
        public virtual ICollection<StoreWallet> StoreWallets { get; set; }
    }
}