// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class Staff
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Account { get; set; }
        public string EncryptedPassword { get; set; }
        public string Title { get; set; }
        public string Role { get; set; }
        public DateOnly RegistrationTime { get; set; }
        public string Photo { get; set; }
        public string Email { get; set; }
        public DateOnly Birthday { get; set; }
    }
}