// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class StoreBusinessHour
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public TimeSpan OpeningTime { get; set; }
        public TimeSpan ClosingTime { get; set; }
        public int OpeningDays { get; set; }

        public virtual Store Store { get; set; }
    }
}