// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class Store
    {
        public Store()
        {
            Carts = new HashSet<Cart>();
            Orders = new HashSet<Order>();
            Products = new HashSet<Product>();
            StoreBusinessHours = new HashSet<StoreBusinessHour>();
            StoreCancellationRecords = new HashSet<StoreCancellationRecord>();
            StoreViolationRecords = new HashSet<StoreViolationRecord>();
            StoreWallets = new HashSet<StoreWallet>();
            StoresCategoriesLists = new HashSet<StoresCategoriesList>();
            Members = new HashSet<Member>();
        }

        public int Id { get; set; }
        public int StorePrincipalId { get; set; }
        public string StoreName { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string Photo { get; set; }

        public virtual StorePrincipal StorePrincipal { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<StoreBusinessHour> StoreBusinessHours { get; set; }
        public virtual ICollection<StoreCancellationRecord> StoreCancellationRecords { get; set; }
        public virtual ICollection<StoreViolationRecord> StoreViolationRecords { get; set; }
        public virtual ICollection<StoreWallet> StoreWallets { get; set; }
        public virtual ICollection<StoresCategoriesList> StoresCategoriesLists { get; set; }

        public virtual ICollection<Member> Members { get; set; }
    }
}