// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class AccountStatues
    {
        public AccountStatues()
        {
            DeliveryDrivers = new HashSet<DeliveryDrivers>();
            Members = new HashSet<Members>();
            StorePrincipals = new HashSet<StorePrincipals>();
        }

        public int Id { get; set; }
        public string Status { get; set; }

        public virtual ICollection<DeliveryDrivers> DeliveryDrivers { get; set; }
        public virtual ICollection<Members> Members { get; set; }
        public virtual ICollection<StorePrincipals> StorePrincipals { get; set; }
    }
}