// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace FoodDlvProject2.EFModels
{
    public partial class AccountStatue
    {
        public AccountStatue()
        {
            DeliveryDrivers = new HashSet<DeliveryDriver>();
            Members = new HashSet<Member>();
            StorePrincipals = new HashSet<StorePrincipal>();
        }

        public int Id { get; set; }
        [Display(Name = "狀態")]
        [Required(ErrorMessage = "{0}必填")]

        [StringLength(30)]
        public string Status { get; set; }

        public virtual ICollection<DeliveryDriver> DeliveryDrivers { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<StorePrincipal> StorePrincipals { get; set; }
    }
}