// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class Cart
    {
        public Cart()
        {
            CartCustomizationItems = new HashSet<CartCustomizationItem>();
        }

        public long Id { get; set; }
        public int MemberId { get; set; }
        public int StoreId { get; set; }
        public long ProductId { get; set; }
        public int Count { get; set; }

        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<CartCustomizationItem> CartCustomizationItems { get; set; }
    }
}