// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class CreditCard
    {
        public int MemberId { get; set; }
        public string BankName { get; set; }
        public string CreditCard1 { get; set; }

        public virtual Member Member { get; set; }
    }
}