// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class CreditCards
    {
        public long MemberId { get; set; }
        public string BankName { get; set; }
        public string CreditCard { get; set; }

        public virtual Members Member { get; set; }
    }
}