// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class DeliveryRecords
    {
        public long DeliveryDriversId { get; set; }
        public long OrderId { get; set; }
        public decimal Milage { get; set; }

        public virtual DeliveryDrivers DeliveryDrivers { get; set; }
        public virtual Orders Order { get; set; }
    }
}