// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class DeliveryDriversRatings
    {
        public int Id { get; set; }
        public long DeliveryDriversId { get; set; }
        public long MemberId { get; set; }
        public long OrderId { get; set; }
        public int? Rating { get; set; }
        public string Comment { get; set; }

        public virtual DeliveryDrivers DeliveryDrivers { get; set; }
        public virtual Members Member { get; set; }
        public virtual Orders Order { get; set; }
    }
}