// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class DeliveryDriversAccountStatues
    {
        public DeliveryDriversAccountStatues()
        {
            DeliveryDrivers = new HashSet<DeliveryDrivers>();
        }

        public int Id { get; set; }
        public string Status { get; set; }

        public virtual ICollection<DeliveryDrivers> DeliveryDrivers { get; set; }
    }
}