// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class DeliveryDrivers
    {
        public DeliveryDrivers()
        {
            CancellationRecords = new HashSet<CancellationRecords>();
            DeliveryDriverReportChats = new HashSet<DeliveryDriverReportChats>();
            Orders = new HashSet<Orders>();
        }

        public long Id { get; set; }
        public int AccountStatusId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public bool Gender { get; set; }
        public string BankAccount { get; set; }
        public string IdentityCode { get; set; }
        public byte[] Idcard { get; set; }
        public byte[] VehicleRegistration { get; set; }
        public byte[] DriverLicense { get; set; }
        public DateTime Birthday { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime RegistrationTime { get; set; }

        public virtual DeliveryDriversAccountStatues AccountStatus { get; set; }
        public virtual ICollection<CancellationRecords> CancellationRecords { get; set; }
        public virtual ICollection<DeliveryDriverReportChats> DeliveryDriverReportChats { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}