// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class DeliveryDriverStatuses
    {
        public long DeliveryDriversId { get; set; }
        public string Status { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }

        public virtual DeliveryDrivers DeliveryDrivers { get; set; }
    }
}