// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace FoodDlvProject2.EFModels
{
    public partial class DriverCancellationRecord
    {
        public int Id { get; set; }
        [Display(Name = "取消項目編號")]
        public int CancellationId { get; set; }
        [Display(Name = "訂單編號")]
        public long OrderId { get; set; }
        [Display(Name = "外送員編號")]
        public int DeliveryDriversId { get; set; }
        [Display(Name = "取消時間")]
        public DateTime CancellationDate { get; set; }

        public virtual DriverCancellation Cancellation { get; set; }
        public virtual DeliveryDriver DeliveryDrivers { get; set; }
        public virtual Order Order { get; set; }
    }
}