// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class DriverCancellations
    {
        public DriverCancellations()
        {
            DriverCancellationRecords = new HashSet<DriverCancellationRecords>();
        }

        public int Id { get; set; }
        public string Reason { get; set; }

        public virtual ICollection<DriverCancellationRecords> DriverCancellationRecords { get; set; }
    }
}