// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class Members
    {
        public Members()
        {
            Orders = new HashSet<Orders>();
            ProductRatings = new HashSet<ProductRatings>();
            ServiceChats = new HashSet<ServiceChats>();
            StoreRatings = new HashSet<StoreRatings>();
        }

        public long Id { get; set; }
        public int AccountStatusId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public bool Gender { get; set; }
        public string IdentityCode { get; set; }
        public DateTime Birthday { get; set; }
        public string Email { get; set; }
        public int Balance { get; set; }
        public string Address { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime RegistrationTime { get; set; }

        public virtual MemberAccountStatues AccountStatus { get; set; }
        public virtual Carts Carts { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ProductRatings> ProductRatings { get; set; }
        public virtual ICollection<ServiceChats> ServiceChats { get; set; }
        public virtual ICollection<StoreRatings> StoreRatings { get; set; }
    }
}