// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class MemberViolationRecord
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int ViolationId { get; set; }
        public long OrderId { get; set; }
        public DateTime ViolationDate { get; set; }

        public virtual Member Member { get; set; }
        public virtual Order Order { get; set; }
        public virtual MemberViolationType Violation { get; set; }
    }
}