// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class Orders
    {
        public Orders()
        {
            DeliveryDriversRatings = new HashSet<DeliveryDriversRatings>();
            DriverCancellationRecords = new HashSet<DriverCancellationRecords>();
            OrderDetails = new HashSet<OrderDetails>();
            OrderStatuses = new HashSet<OrderStatuses>();
            StoreCancellationRecords = new HashSet<StoreCancellationRecords>();
            StoreRatings = new HashSet<StoreRatings>();
        }

        public long Id { get; set; }
        public long MemberId { get; set; }
        public int OrderTotal { get; set; }
        public int DeliveryFee { get; set; }
        public int Total { get; set; }
        public string DeliveryAddress { get; set; }
        public DateTime? OrderTime { get; set; }

        public virtual Members Member { get; set; }
        public virtual ICollection<DeliveryDriversRatings> DeliveryDriversRatings { get; set; }
        public virtual ICollection<DriverCancellationRecords> DriverCancellationRecords { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<OrderStatuses> OrderStatuses { get; set; }
        public virtual ICollection<StoreCancellationRecords> StoreCancellationRecords { get; set; }
        public virtual ICollection<StoreRatings> StoreRatings { get; set; }
    }
}