// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class OrderStatuses
    {
        public int Id { get; set; }
        public long OrderId { get; set; }
        public long DeliveryDriversId { get; set; }
        public string Status { get; set; }
        public DateTime? DeliveryAvailable { get; set; }
        public DateTime? DeliveryStart { get; set; }
        public DateTime? DeliveryEnd { get; set; }
        public DateTime? Comfirm { get; set; }

        public virtual DeliveryDrivers DeliveryDrivers { get; set; }
        public virtual Orders Order { get; set; }
    }
}