// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class Orders
    {
        public Orders()
        {
            CancellationRecords = new HashSet<CancellationRecords>();
            DeliveryDriverReportChats = new HashSet<DeliveryDriverReportChats>();
            OrderDetails = new HashSet<OrderDetails>();
            ServiceChats = new HashSet<ServiceChats>();
        }

        public long Id { get; set; }
        public long DeliveryDriversId { get; set; }
        public long MemberId { get; set; }
        public int OrderStatusesId { get; set; }
        public int OrderTotal { get; set; }
        public int DeliveryFee { get; set; }
        public int Total { get; set; }
        public string DeliveryAddress { get; set; }
        public DateTime OrderTime { get; set; }
        public DateTime DeliveryAvailable { get; set; }
        public DateTime DeliveryStart { get; set; }
        public DateTime DeliveryEnd { get; set; }

        public virtual DeliveryDrivers DeliveryDrivers { get; set; }
        public virtual Members Member { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual ICollection<CancellationRecords> CancellationRecords { get; set; }
        public virtual ICollection<DeliveryDriverReportChats> DeliveryDriverReportChats { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<ServiceChats> ServiceChats { get; set; }
    }
}