// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class ProcessingStatues
    {
        public ProcessingStatues()
        {
            DeliveryDriverReportChats = new HashSet<DeliveryDriverReportChats>();
            ServiceChats = new HashSet<ServiceChats>();
        }

        public int Id { get; set; }
        public string Status { get; set; }

        public virtual ICollection<DeliveryDriverReportChats> DeliveryDriverReportChats { get; set; }
        public virtual ICollection<ServiceChats> ServiceChats { get; set; }
    }
}