// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class Product
    {
        public Product()
        {
            Carts = new HashSet<Cart>();
            OrderDetails = new HashSet<OrderDetail>();
        }

        public long Id { get; set; }
        public int StoreId { get; set; }
        public string ProductName { get; set; }
        public byte[] Photo { get; set; }
        public string ProductContent { get; set; }
        public bool? Status { get; set; }
        public int UnitPrice { get; set; }

        public virtual Store Store { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}