// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class ProductRatings
    {
        public int Id { get; set; }
        public long MemberId { get; set; }
        public long ProductId { get; set; }
        public int Rating { get; set; }

        public virtual Members Member { get; set; }
        public virtual Products Product { get; set; }
    }
}