// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace FoodDlvProject2.EFModels
{
    public partial class Qacategory
    {
        public Qacategory()
        {
            Qas = new HashSet<Qa>();
        }

        public int Id { get; set; }
        [Display(Name = "問題類型")]
        public string Name { get; set; }
        [Display(Name = "編號")]
        public int Displayorder { get; set; }

        public virtual ICollection<Qa> Qas { get; set; }

    }
}