// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class ServiceChats
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public int ServiceId { get; set; }
        public long OrderId { get; set; }
        public int ProcessingStatusId { get; set; }
        public string MemberAsking { get; set; }
        public DateTime Asking { get; set; }
        public string ServiceReplies { get; set; }
        public DateTime Reply { get; set; }

        public virtual Members Member { get; set; }
        public virtual Orders Order { get; set; }
        public virtual ProcessingStatues ProcessingStatus { get; set; }
        public virtual CustomerServices Service { get; set; }
    }
}