// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class Stores
    {
        public Stores()
        {
            Carts = new HashSet<Carts>();
            OrderDetails = new HashSet<OrderDetails>();
            Products = new HashSet<Products>();
            StoreCancellationRecords = new HashSet<StoreCancellationRecords>();
            StoreCategories = new HashSet<StoreCategories>();
            StoreRatings = new HashSet<StoreRatings>();
        }

        public long Id { get; set; }
        public long StorePrincipalId { get; set; }
        public string StoreName { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public DateTime? Opening { get; set; }
        public DateTime? Closing { get; set; }

        public virtual StorePrincipals StorePrincipal { get; set; }
        public virtual ICollection<Carts> Carts { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<StoreCancellationRecords> StoreCancellationRecords { get; set; }
        public virtual ICollection<StoreCategories> StoreCategories { get; set; }
        public virtual ICollection<StoreRatings> StoreRatings { get; set; }
    }
}