// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace FoodDlvProject2.EFModels
{
    public partial class StoreCategory
    {
        public StoreCategory()
        {
            StoresCategoriesLists = new HashSet<StoresCategoriesList>();
        }

        public int Id { get; set; }
        [Display(Name = "類別名稱")]
        public string CategoryName { get; set; }
        [Display(Name = "類別內容")]
        public string CategoryContent { get; set; }

        public virtual ICollection<StoresCategoriesList> StoresCategoriesLists { get; set; }
    }
}