// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class StoreCategories
    {
        public int Id { get; set; }
        public long StoreId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryContent { get; set; }

        public virtual Stores Store { get; set; }
    }
}