// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace FoodDlvProject2.EFModels
{
    public partial class StoreViolationType
    {
        public StoreViolationType()
        {
            StoreViolationRecords = new HashSet<StoreViolationRecord>();
        }

        public int Id { get; set; }
        [Display(Name = "違規內容")]
        public string ViolationContent { get; set; }
        [Display(Name = "詳細內容")]
        public string Content { get; set; }

        public virtual ICollection<StoreViolationRecord> StoreViolationRecords { get; set; }
    }
}