// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FoodDlvProject2.EFModels
{
    public partial class StorePrincipals
    {
        public StorePrincipals()
        {
            Stores = new HashSet<Stores>();
        }

        public long Id { get; set; }
        public int AccountStatusId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public bool Gender { get; set; }
        public string IdentityCode { get; set; }

        [DataType(DataType.Date)]
        public DateTime Birthday { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime RegistrationTime { get; set; }

        public virtual StoreAccountStatues AccountStatus { get; set; }
        public virtual ICollection<Stores> Stores { get; set; }
    }
}