// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class StoresCategoriesList
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int CategoryId { get; set; }

        public virtual StoreCategory Category { get; set; }
        public virtual Store Store { get; set; }
    }
}