// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FoodDlvProject2.EFModels
{
    public partial class Store
    {
        public Store()
        {
            Carts = new HashSet<Cart>();
            Orders = new HashSet<Order>();
            Products = new HashSet<Product>();
            StoreCancellationRecords = new HashSet<StoreCancellationRecord>();
            StoreRatings = new HashSet<StoreRating>();
        }

		public int Id { get; set; }
		public int StorePrincipalId { get; set; }
		[Required]
		[StringLength(50)]
		public string StoreName { get; set; }
		[Required]
		[StringLength(100)]
		public string Address { get; set; }
		[Required]
		[StringLength(10)]
		public string ContactNumber { get; set; }
		public byte[] Photo { get; set; }

		public virtual StorePrincipal StorePrincipal { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<StoreCancellationRecord> StoreCancellationRecords { get; set; }
        public virtual ICollection<StoreRating> StoreRatings { get; set; }
    }
}