// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvProject2.EFModels
{
    public partial class Store
    {
        public Store()
        {
            Carts = new HashSet<Cart>();
            Orders = new HashSet<Order>();
            Products = new HashSet<Product>();
            StoreBusinessHours = new HashSet<StoreBusinessHour>();
            StoreCancellationRecords = new HashSet<StoreCancellationRecord>();
            StoresCategoriesLists = new HashSet<StoresCategoriesList>();
            Members = new HashSet<Member>();
        }

        public int Id { get; set; }
        public int StorePrincipalId { get; set; }
        public string StoreName { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public byte[] Photo { get; set; }

        public virtual StorePrincipal StorePrincipal { get; set; }
        public virtual StoreViolationRecord StoreViolationRecord { get; set; }
        public virtual StoreWallet StoreWallet { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<StoreBusinessHour> StoreBusinessHours { get; set; }
        public virtual ICollection<StoreCancellationRecord> StoreCancellationRecords { get; set; }
        public virtual ICollection<StoresCategoriesList> StoresCategoriesLists { get; set; }

        public virtual ICollection<Member> Members { get; set; }
    }
}