// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace FoodDlvProject2.EFModels
{
    public class DeliveryDriverWorkStatusDTO
    {
        public int Id { get; set; }

        public string Status { get; set; }
    }
    public static class WorkStatusExts
    {
        public static DeliveryDriverWorkStatusDTO ToEntity(this DeliveryDriverWorkStatus source)
        {
            return new DeliveryDriverWorkStatusDTO
            {
                Id = source.Id,
                Status = source.Status,
            };
        }
    }
}