// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class CartDetail
    {
        public CartDetail()
        {
            CartCustomizationItems = new HashSet<CartCustomizationItem>();
        }

        public int Id { get; set; }
        public long ProductId { get; set; }
        public int Qty { get; set; }
        public long CartId { get; set; }

        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<CartCustomizationItem> CartCustomizationItems { get; set; }
    }
}