// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class CartCustomizationItem
    {
        public int Id { get; set; }
        public int CustomizationItemId { get; set; }
        public long ProductId { get; set; }
        public int CartDetailId { get; set; }
        public int Count { get; set; }
        public int IdentifyNum { get; set; }        
    }
}