// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class Member
    {
        public Member()
        {
            AccountAddresses = new HashSet<AccountAddress>();
            Carts = new HashSet<Cart>();
            CreditCards = new HashSet<CreditCard>();
            MemberViolationRecords = new HashSet<MemberViolationRecord>();
            Orders = new HashSet<Order>();
            Stores = new HashSet<Store>();
        }

        public int Id { get; set; }
        public int AccountStatusId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public bool Gender { get; set; }
        public DateTime Birthday { get; set; }
        public string Email { get; set; }
        public int Balance { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime RegistrationTime { get; set; }

        public virtual AccountStatue AccountStatus { get; set; }
        public virtual ICollection<AccountAddress> AccountAddresses { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        public virtual ICollection<MemberViolationRecord> MemberViolationRecords { get; set; }
        public virtual ICollection<Order> Orders { get; set; }

        public virtual ICollection<Store> Stores { get; set; }
    }
}