// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class OrderCustomizationItem
    {
        public int Id { get; set; }
        public int CustomizationItemId { get; set; }
        public long ProductId { get; set; }
        public long OrderDetailId { get; set; }
        public int Count { get; set; }
        public int IdentifyNum { get; set; }

        public virtual ProductCustomizationItem CustomizationItem { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}