// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class ProductCustomizationItem
    {
        public ProductCustomizationItem()
        {
            OrderCustomizationItems = new HashSet<OrderCustomizationItem>();
        }

        public int Id { get; set; }
        public long ProuctId { get; set; }
        public string ItemName { get; set; }
        public int UnitPrice { get; set; }

        public virtual Product Prouct { get; set; }
        public virtual ICollection<OrderCustomizationItem> OrderCustomizationItems { get; set; }
    }
}