// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodDlvAPI.Models
{
    public partial class StorePrincipal
    {
        public StorePrincipal()
        {
            Stores = new HashSet<Store>();
        }

        public int Id { get; set; }
        public int AccountStatusId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public bool Gender { get; set; }
        public DateTime Birthday { get; set; }
        public string Email { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime RegistrationTime { get; set; }

        public virtual AccountStatue AccountStatus { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
    }
}